'use strict';
const colors = ['red', 'white', 'blue'];
console.log('value at colors[0]:', colors[0]);
console.log('value at colors[1]:', colors[1]);
console.log('value at colors[2]:', colors[2]);
// const america = `America is ${colors[0]}, ${colors[1]}, and ${colors[2]}.`;
console.log(`America is ${colors[0]}, ${colors[1]}, and ${colors[2]}.`);
colors[2] = 'green';
// const mexico = `Mexico is ${colors[0]}, ${colors[1]}, and ${colors[2]}.`;
console.log(`Mexico is ${colors[0]}, ${colors[1]}, and ${colors[2]}.`);
console.log('value of colors:', colors);
console.log('typeof colors:', typeof colors);
const students = ['Tré', 'Rex', 'Will', 'Sara'];
const numberOfStudents = students.length;
console.log('value of numberOfStudents:', numberOfStudents);
const lastIndex = students[students.length - 1];
const lastStudent = lastIndex;
console.log('value of lastStudent:', lastStudent);
console.log('value of students:', students);
console.log('typeof students:', typeof students);
